apiVersion: v1
kind: ConfigMap
# this has the contents of the nginix-config file.
# this ConfigMap is mounted to the container as in the deployment.yaml file as a volume
metadata:
  name: nginx-config
  # this is the name referenced in the deployment.yaml file.
  # note the config below gives ability to name the log file dynamically through the .Params.logfile
data:
  nginx.conf: |
    user  nginx;
    worker_processes  auto;

    error_log  /var/log/nginx/error.log notice;
    pid        /var/run/nginx.pid;


    events {
        worker_connections  1024;
    }


    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/{{ .Params.logFile }}  main;

        sendfile        on;
        #tcp_nopush     on;

        keepalive_timeout  65;

        #gzip  on;

        include /etc/nginx/conf.d/*.conf;
    }
